### ISSUE TITLE
AxMenuButton . Language issues

### ISSUE THREAD

**Issue by a1961218921** [ImAxel0/SonsAxLib#1]
`AxMenuButton("中文", PlayerSettings.MaxArmorOfType, null, EBackground.None).Margin(0, 10) `
The display is incorrect .
Everything else is normal.
How do I fix this language problem?
AxMenuButton使用中文会出现异常

![4L2W%58(NT@(G0QRZ44{AEF](https://github.com/ImAxel0/SonsAxLib/assets/174229340/5a146259-3fa4-4eb5-ad41-96e435ddc184)

**Comment by ImAxel0** [comment]
This is a known problem with chinese and maybe other similar languages. I don't know why it behave like that, also the problem could need to be fixed in RedLoader itself and not the lib. Maybe changing `.Text(label)` with `.RichText(label)` could do it. I'm not gonna update for it though.

**Comment by a1961218921** [comment]
Thank you very much for your answer
